### ISSUE TITLE
Support butler --userversion-file option

### ISSUE THREAD

**Issue by svetogam** [KoBeWi/Godot-Project-Builds#11]
Butler has a feature to set the version number from a file. I would like to use this feature with Project Builder. It's documented here: https://itch.io/docs/butler/pushing.html#specifying-your-own-version-number

There's also a feature to set the version number by a command argument, but I don't think that makes sense to support.

Suggested interface:
- Add a field labeled "User Version File" below the "Source Folder" and "Channel" fields. If this is too long then "Version File" is also good.
- Give it a button to select a file.
- Give it a hint when empty that reads "Leave empty to use default version numbering."
- Put something in the documentation reading something like "See the butler manual for the required format of the file."

**Comment by KoBeWi** [comment]
5035025
Also added "Use Project Version" to upload task, which makes it use `application/config/version` when enabled. It's useful with my [Auto Version](https://github.com/KoBeWi/Godot-Auto-Export-Version) addon and I will probably use it in my project.

**Comment by svetogam** [comment]
> Also added "Use Project Version" to upload task, which makes it use application/config/version when enabled.

That's even better. Thanks!
