### ISSUE TITLE
Cannot execute custom task

### ISSUE THREAD

**Issue by svetogam** [KoBeWi/Godot-Project-Builds#14]
The documentation is ambiguous about what a "Custom Task" is. I mean adding a new scene in the Tasks folder.

I'm not sure what the workflow for adding a custom task is supposed to be exactly. I tried a variety of things, but these ended in crashes and errors. The furthest I can get is to copy an existing task, give it a different script with few or no changes, and then I get an error when executing it.

I got 2 different errors this way. One when copying CopyFiles:
```
ERROR: Could not create child process: 
    at: execute_with_pipe (drivers/unix/os_unix.cpp:572)
```
Another when copying PackZIP:
```
ERROR: No loader found for resource: res://Scripts/Tools (expected type: )
    at: _load (core/io/resource_loader.cpp:291)
ERROR: Can't load script: res://Scripts/Tools/
    at: start (main/main.cpp:3530)
```

I *could* get a copied task to run if I did not change its script though.

It would help if you can document a workflow for adding a custom task that works for you. Then I can tell the results of trying it.

**Comment by KoBeWi** [comment]
Can you attach an example custom task that fails?

**Comment by svetogam** [comment]
Here's the one I tried with copying PackZIP, mentioned above. I put both files in the Tasks folder of the Project Builder project.

[FailingTask.zip](https://github.com/user-attachments/files/17402559/FailingTask.zip)

**Comment by KoBeWi** [comment]
The main difference I see is that your task uses external script instead of built-in one. I'm not sure yet why it fails though.

EDIT:
Ah no, your `script_name` field is empty. PackZIP extends special ScriptTask, which has built-in behavior for executing MainLoop scripts. The script name is provided via exported variable.

**Comment by svetogam** [comment]
That was the problem, thanks. The suggested workflow of filling out the empty template works after all. I just assumed that copying an existing task would be easier.

**Comment by KoBeWi** [comment]
In dc2ef1f I added some validation for ScriptTask, so custom tasks won't fail confusingly.
As for creating the tasks themselves, it's actually mentioned in the README: https://github.com/KoBeWi/Godot-Project-Builds?tab=readme-ov-file#custom-tasks
