### ISSUE TITLE
Duplicating a routine can make routines have the same name

### ISSUE THREAD

**Issue by svetogam** [KoBeWi/Godot-Project-Builds#15]
Project Builder prevents routines from having identical names by disabling the Back button in the Routine Builder screen if the routine is given the same name as another routine. But identical names can still be achieved by duplicating a routine.

Steps to reproduce:
1. Add a new routine.
2. Duplicate the routine.
3. Duplicate the same routine again.

Sometimes editing a routine with a non-unique name disables the Back button and highlights the name, and sometimes it doesn't.

On my machine the automatic filenames for copies are "name (copy 1)", "name (copy 2)", "name (copy 3)", etc. The same idea could be used for a fix.

**Comment by KoBeWi** [comment]
c0c209a

**Comment by svetogam** [comment]
I can still get it to make non-unique names.

1. Add routine (routine 1).
2. Duplicate routine 1 (routine 2).
3. Duplicate routine 1 (routine 3).
4. Delete routine 2.
5. Duplicate routine 1 (routine 4).
6. Duplicate routine 1 (routine 5).

Routines 3 and 5 will have the same name: "New Routine (Copy 1)"

**Comment by KoBeWi** [comment]
bb69ec5
