### ISSUE TITLE
Avoid accidental execution better

### ISSUE THREAD

**Issue by svetogam** [KoBeWi/Godot-Project-Builds#2]
Because executing tasks at the wrong time can potentially do some highly undesirable things that can't always be reversed by version control, it's important for the design to make accidental execution unlikely. I found 3 things that could be improved here.

**1**
I found myself double-clicking on my project in the initial project menu, and this led to accidental execution once. I think this was a habit due to Godot's Project List needing double-click to open a project.

One solution would be to follow the convention of Godot's Project List and require double-clicking to open a project. Another, even safer solution would be to add a 1-second transition screen before opening the project.

**2**
 This didn't make me accidentally execute, but the way the Edit button is so close to the Execute button is a little scary.

One solution would be to require double-clicking to execute like the Delete button does. Another solution would be to make the Execute button take up 2 spaces in the grid vertically rather than horizontally. That is, it would take the space of the current Edit button, and the Edit button would be moved above the Duplicate button. This would increase the distance from the center of the Edit and Duplicate buttons to the edge of the Execute button.

**3**
There is a 1 second delay after pressing Execute before execution begins during which it can be canceled. I don't think this is an effective design for preventing accidental execution.

Someone in a state of panic is never going to read "Press Escape to cancel", then find Escape on their keyboard (going from using the mouse), and then press the Escape key within 1 second. This is not very likely even if the user knows ahead of time that Escape cancels execution. And such users are not very likely since it's hard to read and process "Press Escape to cancel" during the short time that it appears. I only became aware of it myself after reading the documentation.

I think the only reasonable designs are to either remove this delay or increase it substantially to make it something like 5 seconds.

---

My personal preferred designs are (1) add a 1-second transition for opening a project, (2) change the Execute button to bigger vertically rather than horizontally, and (3) remove the pre-execution delay completely.

I can make a PR for (2) if you agree. The others I'm less sure how to implement.

**Comment by KoBeWi** [comment]
Resolved by b96190c

> I think the only reasonable designs are to either remove this delay or increase it substantially to make it something like 5 seconds.

I made it configurable with 2 by default. I didn't want the delay to be too long, because accidental executions are uncommon and it's just wasting time otherwise.

**Comment by svetogam** [comment]
I playtested this and have some more suggestions. The big problem I have is with the "input killer" delay.

I approve of the new button layout and the option to set the execution delay. 2 seconds is a good default. It's just enough to make users notice this delay and the possibility of aborting. Then users can modify this delay to be shorter or longer to suit their needs.

The ceiling of 100 seconds is surely too high, but it doesn't actually matter. I would enforce common sense and set it to 10 seconds max, but it really isn't a problem.

A related usability improvement would be to add feedback for the execution delay timer ticking down. This could be a bar, or a circle, or the number decreasing. But this is cosmetic and getting away from the point of this issue.

Releasing the 1 second input killer delay in it's current state would be a mistake. What I had in mind was a transition screen like a loading screen. The problems with it currently are:

1. It gives no feedback that there's a transition state. Instead it drops inputs when the user doesn't expect it, which is annoying.
2. It happens when the main screen is entered from other screens as well, not just from the project list. For example, entering the main screen from the Routine Edit screen gives the same delay, even though this is done by pressing back at the top-left corner. Double-clicking the top-left corner will never trigger accidental execution, so the delay gives no benefit in this case.
3. It's long enough that a user can navigate the routines list and try to edit a new routine, and have their inputs dropped. This happened to me when I was testing it.
4. It drops scrolling mouse-wheel input as well as button-press input. This makes the program unresponsive, not just safe.

I suggested this delay in the context of a 0 or 1 second execution delay, and it was only that long for a transition screen to not be too jarring. Without these things, dropping the input-killing delay completely would be an improvement.

A more safe and still very simple option would be to reduce the delay to 0.4 seconds. 0.4 seconds is the maximum time between clicks for a double-click on my system, and I assume it's common for other systems. It's also too short to be able to navigate the routine menu. I tested it and it wasn't too bad. Above 0.4 seconds, the input killer delay quickly becomes annoying. Though it's still slightly annoying at 0.4 seconds.

Thinking ahead to a best possible interface for this utility, I think that would be to follow a policy of imitating Godot's project list, so habits of using it would transfer perfectly. This would mean to open a project either by double-clicking or first selecting it and then pressing an Edit button. But this option takes more maintainance.

In retrospect I don't think my idea of a transition screen was very good, so I wouldn't recommend it anymore.

**Comment by KoBeWi** [comment]
> Thinking ahead to a best possible interface for this utility, I think that would be to follow a policy of imitating Godot's project list, so habits of using it would transfer perfectly. This would mean to open a project either by double-clicking or first selecting it and then pressing an Edit button. But this option takes more maintainance.

I did not use double-clicking, because there are no options for the project. In Godot you can select project and edit it, run, edit tags etc. Here running is the only possible action, so selecting/double-clicking makes no sense.

I will probably lower the delay as you suggest and make it happen only when opening project for the first time.

**Comment by KoBeWi** [comment]
Done in 44c0390

**Comment by svetogam** [comment]
I tested it and I approve.

And since I didn't mention it yet, thanks for sharing and improving this utility!
