### ISSUE TITLE
Sub-routines in sub-routines do not run tasks after their first task when executed

### ISSUE THREAD

**Issue by svetogam** [KoBeWi/Godot-Project-Builds#7]
This bug is a tongue-twister, so it's easiest to understand following the reproduction steps:

1. Add a new routine (Routine 1) with 2 tasks. For this example, let the first task copy `file1` to `file2` and the second task copy `file1` to `file3`.
2. Add a new routine (Routine 2) with a sub-routine task. Set it to run Routine 1.
3. Add a new routine (Routine 3) with a sub-routine task. Set it to run Routine 2.
4. Execute Routine 3. This will copy `file1` to `file2` but *not* `file1` to `file3`.

This bug seems to happen whenever a sub-routine is set to run a routine that includes a sub-routine that is set to run a routine with more than one task.

**Comment by KoBeWi** [comment]
5fb68b379e6c51dae2527b0faa86e006175d383b
