### ISSUE TITLE
Looping sub-routines to run each other causes crash

### ISSUE THREAD

**Issue by svetogam** [KoBeWi/Godot-Project-Builds#8]
Steps to reproduce:
1. Add 2 routines with sub-routine tasks set to run each other.
2. Execute either of the 2 routines.

This makes Project Builder stall for a while and then crash.

Nothing bad such as data loss seems to happen, and I didn't really expect anything else. But it would be better if the program didn't crash and gave an error instead.

**Comment by KoBeWi** [comment]
2a727e6

**Comment by svetogam** [comment]
I can still get it to crash by adding subroutines in a cycle and then executing another subroutine pointing into them.

Steps to reproduce:
1. Add routines 1 and 2 with sub-routine tasks set to run each other.
2. Add routine 3 with sub-routine task to run either routine 1 or 2.
3. Execute routine 3.

Maybe this isn't actually worth fixing. I don't know what the complexity of a full solution would be, and any user doing this shouldn't be surprised if they get a crash.

**Comment by KoBeWi** [comment]
c71fbd4 🤦‍♂️
