### ISSUE TITLE
Allow relative paths for arguments in custom command task

### ISSUE THREAD

**Issue by svetogam** [KoBeWi/Godot-Project-Builds#9]
The readme for the custom command task reads:

> Command: Command that will be executed. It will be invoked like from a terminal, but the working directory is undefined, so you should either use absolute path or global commands.

Relative paths are very valuable, to the point that I think they should be considered a core feature of the custom command task. It's just not complete without them. The working directory could be defined to be the root of the Godot project folder, where the `project.godot` file is. Is this difficult to do for some reason?

If it's somehow not viable to get this to work in a simple way, then relative paths are important enough that some sort of workaround would be worth it. For example, the user could set the path to the project manually in Local Config. This wouldn't be ideal, but it would be much better than not allowing relative paths.

**Comment by KoBeWi** [comment]
When running from command line, the working directory is the directory you started from. When running from plugin, the working directory is either project directory or Godot directory or project builder's directory, I don't know which one. There is no way to set a working directory when running executable. I could add some placeholder for project path, which could be used in a command and automatically replaced, so e.g. you could do `executable {project}/something` and `{project}` would get replaced with absolute project's path.

**Comment by svetogam** [comment]
Having a placeholder like that sounds good to me.

**Comment by KoBeWi** [comment]
13ab58e

**Comment by svetogam** [comment]
This feature could be better. I have 3 problems with it.

1. The placeholder is replaced in editing routines. This can add a long path that requires scrolling through, and that makes custom commands hard to read.
2. The placeholder is replaced in the local config/data file. This makes the file hard to reuse and share between projects.
3. Moving the project folder will still break relative paths of this kind.

A fix could be to keep the unconverted placeholder and only replace it in copies of the string used for execution. Hopefully that's easy to do.

**Comment by KoBeWi** [comment]
ed3151a
Sorry, it was a mistake.

**Comment by svetogam** [comment]
No problem. Thanks!
